title: Blog title
author: Dzmitry
email: no@email.com
description: > # this means to ignore newlines until "baseurl:"
  Some awesome description.
  All line brakes are ignored

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
